--2021-11-01
--xiaohu
--学习练手代码，仅供参考，欢迎交流
--数据库建表暂时不要使用，字段未调整

CREATE database IF NOT EXISTS `myAdminTemplate` DEFAULT CHARSET=utf8;
USE `myAdminTemplate`;

DROP TABLE IF EXISTS `SYS_USER`;
CREATE TABLE `SYS_USER`(
	`ID` varchar(32) NOT NULL,
	`USERNAME` varchar(255) NOT NULL,
	`PASSWORD` varchar(255) NOT NULL,
	`SALT` varchar(255) NOT NULL,
	 PRIMARY KEY(`ID`)
)ENGINE = InnoDB DEFAULT CHARSET=utf8;


DROP TABLE IF EXISTS `SYSTEM_INFO`;
CREATE TABLE `SYSTEM_INFO` (
  `ID` varchar(32) NOT NULL,
  `HOST_NAME` varchar(64) DEFAULT NULL,
  `OS_NAME` varchar(64) DEFAULT NULL,
  `VERSION` varchar(64) DEFAULT NULL,
  `CPU_CORE_NUM` varchar(10) DEFAULT NULL,
  `CREATE_TIME` timestamp NULL DEFAULT NULL,
  `STATE` varchar(1) DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS `SYS_ROLE`;
CREATE TABLE `SYS_ROLE`(
  `ID` varchar(32) NOT NULL,
  `ROLE_NAME` varchar(32) NOT NULL,
  `DESCRIPTION` varchar(1024),
  PRIMARY KEY(`ID`)
)ENGINE=InnoDB DEFAULT CHARSET=utf8;


DROP TABLE IF EXISTS `SYS_USER_ROLE`;
CREATE TABLE `SYS_USER_ROLE`(
  `ID` varchar(32) NOT NULL,
  `USER_ID` varchar(32) NOT NULL,
  `ROLE_ID` varchar(32) NOT NULL,
  PRIMARY KEY(`ID`)
)ENGINE=InnoDB DEFAULT CHARSET=utf8;
